before_install:
  - env
  - openssl version
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"

install:
  - curl -Lo macpython.pkg https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg
  - sudo installer -pkg macpython.pkg -target /
  - /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install virtualenv


script:
  - /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install .
  - /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 stciphers.py

notifications:
  email: false

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

jobs:
  include:
    - language: generic
      os: osx
      osx_image: xcode7.3
    - language: generic
      os: osx
      osx_image: xcode8.3
    - language: generic
      os: osx
      osx_image: xcode9.3
    - language: generic
      os: osx
      osx_image: xcode10.2
    - language: generic
      os: osx
      osx_image: xcode11.4
    - language: generic
      os: osx
      osx_image: xcode12.2
