language: python
os: linux
dist: xenial

cache:
  directories:
  - ${HOME}/.cache

notifications:
  email: false

env:
  global:
    - PYPI_USERNAME=urllib3
    # PYPI_PASSWORD is set in Travis control panel.

jobs:
  allow_failures:
    - python: nightly
  include:
    - python: 3.7
      stage: deploy
      script:
        - ./ci/deploy.sh

stages:
  # Deploy on any tags
  - name: deploy
    if: tag IS present AND tag =~ /^(\d+\.\d+(?:.\d+)?)$/ AND repo = urllib3/urllib3
