import ctypes
from enum import Enum, auto, unique

from urllib3.contrib.securetransport import Security, SecurityConst, _assert_no_error


@unique
class Cipher(Enum):
    def _generate_next_value_(name, start, count, last_values):
        return name

    SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = auto()
    SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA = auto()
    SSL_DHE_DSS_WITH_DES_CBC_SHA = auto()
    SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = auto()
    SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA = auto()
    SSL_DHE_RSA_WITH_DES_CBC_SHA = auto()
    SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = auto()
    SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA = auto()
    SSL_DH_DSS_WITH_DES_CBC_SHA = auto()
    SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = auto()
    SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA = auto()
    SSL_DH_RSA_WITH_DES_CBC_SHA = auto()
    SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA = auto()
    SSL_DH_anon_EXPORT_WITH_RC4_40_MD5 = auto()
    SSL_DH_anon_WITH_3DES_EDE_CBC_SHA = auto()
    SSL_DH_anon_WITH_DES_CBC_SHA = auto()
    SSL_DH_anon_WITH_RC4_128_MD5 = auto()
    SSL_FORTEZZA_DMS_WITH_FORTEZZA_CBC_SHA = auto()
    SSL_FORTEZZA_DMS_WITH_NULL_SHA = auto()
    SSL_NO_SUCH_CIPHERSUITE = auto()
    SSL_NULL_WITH_NULL_NULL = auto()
    SSL_RSA_EXPORT_WITH_DES40_CBC_SHA = auto()
    SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = auto()
    SSL_RSA_EXPORT_WITH_RC4_40_MD5 = auto()
    SSL_RSA_WITH_3DES_EDE_CBC_MD5 = auto()
    SSL_RSA_WITH_3DES_EDE_CBC_SHA = auto()
    SSL_RSA_WITH_DES_CBC_MD5 = auto()
    SSL_RSA_WITH_DES_CBC_SHA = auto()
    SSL_RSA_WITH_IDEA_CBC_MD5 = auto()
    SSL_RSA_WITH_IDEA_CBC_SHA = auto()
    SSL_RSA_WITH_NULL_MD5 = auto()
    SSL_RSA_WITH_NULL_SHA = auto()
    SSL_RSA_WITH_RC2_CBC_MD5 = auto()
    SSL_RSA_WITH_RC4_128_MD5 = auto()
    SSL_RSA_WITH_RC4_128_SHA = auto()
    TLS_AES_128_CCM_8_SHA256 = 0x1305
    TLS_AES_128_CCM_SHA256 = 0x1304
    TLS_AES_128_GCM_SHA256 = 0x1301
    TLS_AES_256_GCM_SHA384 = 0x1302
    TLS_CHACHA20_POLY1305_SHA256 = auto()
    TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA = auto()
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = auto()
    TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = auto()
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA = auto()
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = auto()
    TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = auto()
    TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA = auto()
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = auto()
    TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = auto()
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA = auto()
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = auto()
    TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = auto()
    TLS_DHE_PSK_WITH_NULL_SHA = auto()
    TLS_DHE_PSK_WITH_NULL_SHA256 = auto()
    TLS_DHE_PSK_WITH_NULL_SHA384 = auto()
    TLS_DHE_PSK_WITH_RC4_128_SHA = auto()
    TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 0x0033
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 0x0067
    TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 0x009E
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 0x0039
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 0x006B
    TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 0x009F
    TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_DH_DSS_WITH_AES_128_CBC_SHA = auto()
    TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = auto()
    TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = auto()
    TLS_DH_DSS_WITH_AES_256_CBC_SHA = auto()
    TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = auto()
    TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = auto()
    TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_DH_RSA_WITH_AES_128_CBC_SHA = auto()
    TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = auto()
    TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = auto()
    TLS_DH_RSA_WITH_AES_256_CBC_SHA = auto()
    TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = auto()
    TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = auto()
    TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_DH_anon_WITH_AES_128_CBC_SHA = auto()
    TLS_DH_anon_WITH_AES_128_CBC_SHA256 = auto()
    TLS_DH_anon_WITH_AES_128_GCM_SHA256 = auto()
    TLS_DH_anon_WITH_AES_256_CBC_SHA = auto()
    TLS_DH_anon_WITH_AES_256_CBC_SHA256 = auto()
    TLS_DH_anon_WITH_AES_256_GCM_SHA384 = auto()
    TLS_DH_anon_WITH_RC4_128_MD5 = auto()
    TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 0xC008
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 0xC009
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 0xC023
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 0xC02B
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 0xC00A
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 0xC024
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 0xC02C
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 0xCCA9
    TLS_ECDHE_ECDSA_WITH_NULL_SHA = auto()
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = auto()
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = auto()
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = auto()
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 0xC012
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 0xC013
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 0xC027
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 0xC02F
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 0xC014
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 0xC028
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 0xC030
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 0xCCA8
    TLS_ECDHE_RSA_WITH_NULL_SHA = auto()
    TLS_ECDHE_RSA_WITH_RC4_128_SHA = auto()
    TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = auto()
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = auto()
    TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = auto()
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = auto()
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = auto()
    TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = auto()
    TLS_ECDH_ECDSA_WITH_NULL_SHA = auto()
    TLS_ECDH_ECDSA_WITH_RC4_128_SHA = auto()
    TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = auto()
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = auto()
    TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = auto()
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = auto()
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = auto()
    TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = auto()
    TLS_ECDH_RSA_WITH_NULL_SHA = auto()
    TLS_ECDH_RSA_WITH_RC4_128_SHA = auto()
    TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_ECDH_anon_WITH_AES_128_CBC_SHA = auto()
    TLS_ECDH_anon_WITH_AES_256_CBC_SHA = auto()
    TLS_ECDH_anon_WITH_NULL_SHA = auto()
    TLS_ECDH_anon_WITH_RC4_128_SHA = auto()
    TLS_EMPTY_RENEGOTIATION_INFO_SCSV = auto()
    TLS_NULL_WITH_NULL_NULL = auto()
    TLS_PSK_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_PSK_WITH_AES_128_CBC_SHA = auto()
    TLS_PSK_WITH_AES_128_CBC_SHA256 = auto()
    TLS_PSK_WITH_AES_128_GCM_SHA256 = auto()
    TLS_PSK_WITH_AES_256_CBC_SHA = auto()
    TLS_PSK_WITH_AES_256_CBC_SHA384 = auto()
    TLS_PSK_WITH_AES_256_GCM_SHA384 = auto()
    TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 = auto()
    TLS_PSK_WITH_NULL_SHA = auto()
    TLS_PSK_WITH_NULL_SHA256 = 0x00B0
    TLS_PSK_WITH_NULL_SHA384 = auto()
    TLS_PSK_WITH_RC4_128_SHA = auto()
    TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = auto()
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA = auto()
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = auto()
    TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = auto()
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA = auto()
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = auto()
    TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = auto()
    TLS_RSA_PSK_WITH_NULL_SHA = auto()
    TLS_RSA_PSK_WITH_NULL_SHA256 = auto()
    TLS_RSA_PSK_WITH_NULL_SHA384 = auto()
    TLS_RSA_PSK_WITH_RC4_128_SHA = auto()
    TLS_RSA_WITH_3DES_EDE_CBC_SHA = 0x000A
    TLS_RSA_WITH_AES_128_CBC_SHA = 0x002F
    TLS_RSA_WITH_AES_128_CBC_SHA256 = 0x003C
    TLS_RSA_WITH_AES_128_GCM_SHA256 = 0x009C
    TLS_RSA_WITH_AES_256_CBC_SHA = 0x0035
    TLS_RSA_WITH_AES_256_CBC_SHA256 = 0x003D
    TLS_RSA_WITH_AES_256_GCM_SHA384 = 0x009D
    TLS_RSA_WITH_NULL_MD5 = auto()
    TLS_RSA_WITH_NULL_SHA = auto()
    TLS_RSA_WITH_NULL_SHA256 = auto()
    TLS_RSA_WITH_RC4_128_MD5 = auto()
    TLS_RSA_WITH_RC4_128_SHA = auto()


ssl_context = context = Security.SSLCreateContext(
    None, SecurityConst.kSSLClientSide, SecurityConst.kSSLStreamType
)

# get number of supported ciphers
numCiphers = ctypes.c_size_t(0)
result = Security.SSLGetNumberEnabledCiphers(context, ctypes.byref(numCiphers))
_assert_no_error(result)
# get actual ciphers
ciphers = (Security.SSLCipherSuite * numCiphers.value)()
result = Security.SSLGetEnabledCiphers(
    context, ctypes.cast(ciphers, ctypes.POINTER(ctypes.c_uint32)), numCiphers
)
_assert_no_error(result)
for c in ciphers:
    print(Cipher(c).name)
